quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASSWORD:root}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://mysql:3306/flashcards?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/swagger